In [7]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

# Matrix Addition
print('\nMatrix Addition')
A = np.array([[5,8],[6,9]])
print(A)
B = np.array([[3,2],[4,-1]])
print(B)
C = A+B
print(C)

# Matrix Subtraction
print('\nMatrix Subtraction')
D = A - B
print(D)

# Matrix-Scalar Multiplication
print('\nMatrix-Scalar Multiplication')
A = np.array([[5,8],[6,9]])
print(A)
b = 2
E = A*2
print(E)

# Matrix-Vector Multiplication
print('\nMatrix Multiplication')
A = np.array([[5,8],[6,9]])
print(A)
v = np.array([[3,2],[4,-1]])
print(v)
print(A@v)

# Taking transpose
print('\nTaking transpose')
print(A)
B = A.T
print(B)

# Matrix Inverse
print('\nMatrix Inverse')
print(A)
B = np.linalg.inv(A)
print(B)

# Identity Matrix
print('\nIdentity Matrix')
I3 = np.eye(3)
print(I3)


Matrix Addition
[[5 8]
 [6 9]]
[[ 3  2]
 [ 4 -1]]
[[ 8 10]
 [10  8]]

Matrix Subtraction
[[ 2  6]
 [ 2 10]]

Matrix-Scalar Multiplication
[[5 8]
 [6 9]]
[[10 16]
 [12 18]]

Matrix Multiplication
[[5 8]
 [6 9]]
[[ 3  2]
 [ 4 -1]]
[[47  2]
 [54  3]]

Taking transpose
[[5 8]
 [6 9]]
[[5 6]
 [8 9]]

Matrix Inverse
[[5 8]
 [6 9]]
[[-3.     2.667]
 [ 2.    -1.667]]

Identity Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
