In [2]:
import numpy as np

data = np.array([[15.5, 33.2],[2.4, 59.8],[8.2, 22.2]])
print(data,'\n')
print('Shape:', data.shape,'\n')

mean_vector = np.mean(data, axis=0)
print('Mean vector: \n', mean_vector,'\n')

C = np.cov(data, rowvar=False)
print('Covariance matrix: \n', C,'\n')

R = np.corrcoef(data, rowvar=0)
print('Correlation matrix: \n', R,'\n')

generalisedSampleVariance = (C[0,0]*C[1,1] - C[0,1]**2)
print('Generalised sample variance: ', generalisedSampleVariance,'\n')

totalSampleVariance = (C[0,0] + C[1,1])
print('Total sample variance: ', totalSampleVariance,'\n')

[[15.5 33.2]
 [ 2.4 59.8]
 [ 8.2 22.2]] 

Shape: (3, 2) 

Mean vector: 
 [ 8.7 38.4] 

Covariance matrix: 
 [[ 43.09 -81.04]
 [-81.04 373.72]] 

Correlation matrix: 
 [[ 1.         -0.63861338]
 [-0.63861338  1.        ]] 

Generalised sample variance:  9536.1132 

Total sample variance:  416.8099999999999 

