### Singular Value Decomposition

We can use numpy.linalg.svd to find a singular value decomposition for a matrix $\mathbf{A}=\begin{bmatrix}1 & 2 & 1 \\ 0 & 1 & 4 \\ 1 & 4 & 9 \\ 1 & -1 & -11 \end{bmatrix}$.

In [12]:
import matplotlib.pyplot as plt
import matplotlib.image as image
import numpy as np
from sympy import nsimplify, Matrix
# Define matrix A
# A = np.array([[1,2,1],[0,1,4],[1,4,9],[1,-1,-11]])
A = np.array([[1,1],[0,1],[1,0]])
transpose = np.transpose(A)
ATA = transpose@A
m,n = np.shape(A)
U,S,VT = np.linalg.svd(A)
V = VT.T

eigvals, eigvecs = np.linalg.eig(ATA)
print("Eigenvalues are: ", eigvals)
print("Eigenvectors are: ", eigvecs)

eigvecs = Matrix(eigvecs)
eigvecs_surd = eigvecs.applyfunc(nsimplify)
print("Eigenvectors are: ", eigvecs_surd, '\n')

if m!=n:
    Sigma = np.zeros([m,n])
    for row in range(len(S)):
        Sigma[row,row]=S[row]       
else:
    Sigma = np.diag(S)

print("A is: ", A)  
print("U is: ", U)
print("Sigma (E) is: ", S)
print("V is: ", V)
print(format(Sigma[0,1], "0.2f"), '\n')
    
Sigma = Matrix(Sigma)
Sigma_surd = Sigma.applyfunc(nsimplify)
    
U = Matrix(U)
U_surd = U.applyfunc(nsimplify)

V = Matrix(V)
V_surd = V.applyfunc(nsimplify)

print("A is: ", A)
print("U is: ", U_surd)
print("Sigma (E) is: ", Sigma_surd)
print("V is: ", V_surd)

Eigenvalues are:  [3. 1.]
Eigenvectors are:  [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Eigenvectors are:  Matrix([[sqrt(2)/2, -sqrt(2)/2], [sqrt(2)/2, sqrt(2)/2]]) 

A is:  [[1 1]
 [0 1]
 [1 0]]
U is:  [[-8.16496581e-01 -1.66533454e-16 -5.77350269e-01]
 [-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]
Sigma (E) is:  [1.73205081 1.        ]
V is:  [[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]
0.00 

A is:  [[1 1]
 [0 1]
 [1 0]]
U is:  Matrix([[-sqrt(6)/3, -166533453693773/1000000000000000000000000000000, -sqrt(3)/3], [-sqrt(6)/6, -sqrt(2)/2, sqrt(3)/3], [-sqrt(6)/6, sqrt(2)/2, sqrt(3)/3]])
Sigma (E) is:  Matrix([[sqrt(3), 0], [0, 1], [0, 0]])
V is:  Matrix([[-sqrt(2)/2, sqrt(2)/2], [-sqrt(2)/2, -sqrt(2)/2]])


We can verify that $\mathbf{A}=\mathbf{U\Sigma V}^T$.

In [9]:
print(np.matmul(np.matmul(U,Sigma),VT))

[[1.00000000000000 0.999999999999999]
 [5.55111512312578e-17 1.00000000000000]
 [1.00000000000000 -5.55111512312578e-17]]


### Reduced Singular Value Decomposition

Remove columns in $\mathbf{U}$ and $\mathbf{V}$ to obtain a reduced SVD for $\mathbf{A}$, $\mathbf{A}=\mathbf{U}_r\mathbf{\Sigma}_r \mathbf{V}_r^T$.

In [10]:
# select only first r columns of U and V and first r columns and rows of Sigma
r = 2
U_r = U[:,0:r]
Sigma_r = Sigma[0:r,0:r]
V_r = V[:,0:r]
print("U_r is: ", U_r)
print("Sigma_r is: ", Sigma_r)
print("V_r is: ", V_r)

U_r is:  Matrix([[-0.816496580927726, -1.66533453693773e-16], [-0.408248290463863, -0.707106781186547], [-0.408248290463863, 0.707106781186547]])
Sigma_r is:  Matrix([[1.73205080756888, 0], [0, 1.00000000000000]])
V_r is:  Matrix([[-0.707106781186548, 0.707106781186547], [-0.707106781186547, -0.707106781186548]])


We can verify that $\mathbf{A}=\mathbf{U}_r\mathbf{\Sigma}_r \mathbf{V}_r^T$.

In [11]:
print(np.matmul(np.matmul(U_r,Sigma_r),V_r.T))

[[1.00000000000000 0.999999999999999]
 [5.55111512312578e-17 1.00000000000000]
 [1.00000000000000 -5.55111512312578e-17]]
