# Practical 4: Eigenvalues and Eigenvectors


### Eigenvalues & Eigenvectors of a Square Matrix


In [1]:
import numpy as np
# Define square matrix A
A = np.array([[1, -1],[2,2]])
print(A)
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues are: ", eigvals)
print("Eigenvectors are: ", eigvecs)


[[ 1 -1]
 [ 2  2]]
Eigenvalues are:  [1.5+1.32287566j 1.5-1.32287566j]
Eigenvectors are:  [[-0.20412415+0.54006172j -0.20412415-0.54006172j]
 [ 0.81649658+0.j          0.81649658-0.j        ]]


In [2]:
import numpy as np
# Define square matrix A
A = np.array([[2, 0, 1], [-1, 4, -1], [-1, 2, 0]])
print(A)
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues are: ", eigvals)
print("Eigenvectors are: ", eigvecs)


[[ 2  0  1]
 [-1  4 -1]
 [-1  2  0]]
Eigenvalues are:  [3. 2. 1.]
Eigenvectors are:  [[ 4.08248290e-01  8.94427191e-01 -7.07106781e-01]
 [ 8.16496581e-01  4.47213595e-01 -1.67849944e-16]
 [ 4.08248290e-01  5.30898698e-16  7.07106781e-01]]


So the eigenvalues of A are: 3, 2, and 1
Notice that the corresponding eigenvectors are given in columns and are
normalized to unit length.


In [3]:
# The first eigenvalue is 3
# Its corresponding eigenvector is in column 1 of eigvecs
print("First eigenvalue is: ", eigvals[0])  # subject to rounding errors
print("Corresponding eigenvector is: ", eigvecs[:, 0])
print("Its magnitude is: ", np.linalg.norm(
    eigvecs[:, 0]))  # subject to rounding error


First eigenvalue is:  2.999999999999999
Corresponding eigenvector is:  [0.40824829 0.81649658 0.40824829]
Its magnitude is:  1.0


To check whether the first vector and first value are indeed the eigenvector and eigenvalue
of A, we do the following:


In [4]:
# Find Av
B = np.dot(A, eigvecs[:, 0])
print("Av is: ", B)

# Find lambda*v
C = eigvals[0] * eigvecs[:, 0]
print("lambda*v is: ", C)


Av is:  [1.22474487 2.44948974 1.22474487]
lambda*v is:  [1.22474487 2.44948974 1.22474487]


Notice that the two answers are the same, confirming that the first vector is an eigenvector
corresponding to the first eigenvalue.


### Task 1


Some properties of eigenvalues include:<br>
• The sum of eigenvalues of a matrix equals its trace.<br>
• The product of eigenvalues equals its determinant.<br><br>
Verify the properties above using the matrix $\mathbf{A}=\begin{bmatrix}2 & 1 & 2 \\ 2 & 2 & -2 \\ 3 & 1 & 1 \end{bmatrix}$


In [5]:
import numpy as np
A = np.array([[2, 1, 2], [2, 2, -2], [3, 1, 1]])
trace = A.trace()
det = np.linalg.det(A)
eigvals, eigvecs = np.linalg.eig(A)

print(
    f"The sum of eigenvalues of matrix is equals to trace: {round(sum(eigvals),0) == trace}")
print(
    f"The product of eigenvalues equals its determinant: {round(np.product(eigvals),0) == round(det,0)}")


The sum of eigenvalues of matrix is equals to trace: True
The product of eigenvalues equals its determinant: True


### Task 2


**Symmetric Matrix**: The eigenvalues of a symmetrical matrix are always real and the eigenvectors are always orthogonal. Verify this in Python for the matrix A below.<br>
$$\mathbf{A}=\begin{bmatrix}1 & -1 & 0 \\ -1 & 2 & -1 \\ 0 & -1 & 1 \end{bmatrix}$$


In [6]:
import numpy as np
A = np.array([[1, -1, 0], [-1, 2, -1], [0, -1, 1]])
eigvals, eigvecs = np.linalg.eig(A)

for i in range(len(A) - 1):
    for j in range(i + 1, len(A)):
        print(eigvecs[i].T.dot(eigvecs[j]))


-2.295282842158142e-17
1.1102230246251565e-16
1.3397513088409747e-16
