# Practical 1: Vectors & Matrices


Many machine learning algorithms make use of matrices to store and process data. 
For example, a deep learning algorithm makes use of matrices to store inputs such as 
images, tweets, or text to solve problems. An artificial neural network makes use of 
matrices to store information such as weights during training. A familiarity with 
matrices and vectors is hence important.

In this practical we will learn some of the fundamentals of matrices and vectors.

A **vector** can be represented as a list in Python.
For example:

In [1]:
v = [ 1, 4, 2]
print(v)

[1, 4, 2]


A **matrix** is a 2D array which stores numbers. 
Alternatively, a matrix can also be thought of as 
a list of vectors.

An example:

In [2]:
A = [[1,4,2],[0,6,3],[3,5,6]]
print(A)

[[1, 4, 2], [0, 6, 3], [3, 5, 6]]


An alternative way to work with vectors and matrices is
to use the **NumPy** module in Python.

In [3]:
import numpy as np
v = np.array([[1],
               [4],
               [2]])
print(v)
A = np.array([[1,4, 2], [0, 6, 3],[3, 5, 6]])
print(A)

[[1]
 [4]
 [2]]
[[1 4 2]
 [0 6 3]
 [3 5 6]]


We can check the order of **A** and **v** as follows:

In [4]:
print("A if of dimension: ", A.shape)
print("v is of dimension: ", v.shape)

A if of dimension:  (3, 3)
v is of dimension:  (3, 1)


There are a lot of matrix operations which we can make use
of in **NumPy**. Some examples are given below.

In [5]:
# Matrix Addition
A = np.array([[5,8],[6,9]])
print(A)
B = np.array([[3,2],[4,-1]])
print(B)
C = A+B
print(C)

[[5 8]
 [6 9]]
[[ 3  2]
 [ 4 -1]]
[[ 8 10]
 [10  8]]


In [6]:
# Matrix Subtraction
D = A - B
print(D)

[[ 2  6]
 [ 2 10]]


In [7]:
# Matrix-Scalar Multiplication
A = np.array([[5,8],[6,9]])
print(A)
b = 2
E = A*2
print(E)

[[5 8]
 [6 9]]
[[10 16]
 [12 18]]


In [8]:
# Matrix-Vector Multiplication
A = np.array([[5,8],[6,9]])
print(A)
v = np.array([[1],[4]])
print(v)
w = np.dot(A,v)
print(w)

[[5 8]
 [6 9]]
[[1]
 [4]]
[[37]
 [42]]


In [9]:
# Matrix-Matrix Multiplication
A = np.array([[5,8],[6,9]])
print(A)
B = np.array([[3,2],[4,-1]])
print(B)
C = np.dot(A,B)
print(C)

[[5 8]
 [6 9]]
[[ 3  2]
 [ 4 -1]]
[[47  2]
 [54  3]]


In [10]:
# Taking transpose
print(A)
B = A.T
print(B)

[[5 8]
 [6 9]]
[[5 6]
 [8 9]]


In [11]:
# Finding trace
print(A)
traceA = np.trace(A)
print(traceA)

[[5 8]
 [6 9]]
14


In [12]:
# Finding Matrix Determinant
A = np.array([[5,8],[6,9]])
print(A)
detA = np.linalg.det(A)
print(detA)

[[5 8]
 [6 9]]
-3.000000000000005


In [13]:
# Matrix Inverse
print(A)
B = np.linalg.inv(A)
print(B)

[[5 8]
 [6 9]]
[[-3.          2.66666667]
 [ 2.         -1.66666667]]


In [ ]:
A = np.array([[5,8],[6,9]])

An **identity matrix** of order 3 can be created as follows:

In [14]:
I3 = np.eye(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


To create a 2x3 matrix of random numbers drawn from a normal distribution with mean 0 and variance 1, we use:

In [15]:
weights = np.random.randn(2,3)
print(weights)

[[-0.27677063 -0.72996266 -0.58227823]
 [ 1.25355498  0.95829834 -0.14723111]]


A 3x3 **diagonal matrix** with (1, 5, 1) along its principal diagonal can be constructed as follows:

In [16]:
A = np.diag((1, 5, 1))
print(A)

[[1 0 0]
 [0 5 0]
 [0 0 1]]


To create a 1x3 matrix of **ones**, we can do as follows:

In [17]:
print(np.ones((1,3)))

[[1. 1. 1.]]


### Task 1
Enter the matrix $\mathbf{A}=\begin{bmatrix}1 & 2 & 4 & 5 \\ 0 & 1 & 5 & -2 \\ 2 & -4 & 3 & 9 \end{bmatrix}$ in Python.<br>
Display the following: <br>
(a)  the size of the matrix $\mathbf{A}$ <br>
(b)  $a_{23}$, $a_{32}$ and $a_{34}$ <br>
(c)  row 1 and column 4 of $\mathbf{A}$

In [18]:
A = np.array([[1,2,4,5],[0,1,5,-2],[2,-4,3,9]])
A.shape

(3, 4)

In [19]:
print(f"A23 = {A[2-1,3-1]}")
print(f"A32 = {A[3-1,2-1]}")
print(f"A34 = {A[3-1,4-1]}")

A23 = 5
A32 = -4
A34 = 9


In [20]:
print(f"row 1 = {A[1-1]}")
print(f"col 4 = {A[:,4-1]}")

row 1 = [1 2 4 5]
col 4 = [ 5 -2  9]


### Task 2###
Enter the following matrices in Python. <br>
$\mathbf{A}=\begin{bmatrix}7 & -3 \\ 2 & 1 \\ 9 & -6 \\ -3 & 2 \end{bmatrix} , 
\mathbf{B}=\begin{bmatrix}2 \\ 5 \end{bmatrix} , 
\mathbf{C}=\begin{bmatrix}5 & 1 & -8 & 4 \\ 2 & 7 & -3 & 5\end{bmatrix}$ <br>
Compute each of the following expression if possible. <br>
(a) $\mathbf{AC}$ <br>
(b) $\mathbf{AB}$ <br>
(c) $\mathbf{A} + \mathbf{C}^T$ <br>
(d) $\mathbf{BA}$ <br>
(e) $\mathbf{AA}^T + \mathbf{C}^T\mathbf{C}$ <br>
(f) $\mathbf{A} + 2\mathbf{C}^T$

In [21]:
A = np.array([[7, -3], [2, 1], [9, -6], [-3, 2]])
B = np.array([[2],[5]])
C = np.array([[5,1,-8,4],[2,7,-3,5]])
A.dot(C)

array([[ 29, -14, -47,  13],
       [ 12,   9, -19,  13],
       [ 33, -33, -54,   6],
       [-11,  11,  18,  -2]])

In [22]:
A.dot(B)

array([[ -1],
       [  9],
       [-12],
       [  4]])

In [23]:
A + C.T

array([[12, -1],
       [ 3,  8],
       [ 1, -9],
       [ 1,  7]])

In [24]:
B.dot(A)

ValueError: shapes (2,1) and (4,2) not aligned: 1 (dim 1) != 4 (dim 0)

In [25]:
A.dot(A.T) + C.T.dot(C)

array([[ 87,  30,  35,   3],
       [ 30,  55, -17,  35],
       [ 35, -17, 190, -86],
       [  3,  35, -86,  54]])

In [26]:
A + 2 * C.T

array([[ 17,   1],
       [  4,  15],
       [ -7, -12],
       [  5,  12]])

### Task 3###
Determine if each of the following matrices is singular.<br>
(a) $\mathbf{A}=\begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$ <br><br>
(b) $\mathbf{A}=\begin{bmatrix}0 & 1 & 3 & 4 \\ -2 & 1 & 2 & 1 \\ 2 & 0 & 1 & 0 \\ 0 & 8 & 3 & 1 \end{bmatrix}$ <br>

In [27]:
A = np.arange(1,10,1).reshape(3,3)
np.linalg.det(A)

6.66133814775094e-16

In [ ]:
A = np.array([[0,1,3,4],[-2,1,2,1],[2,0,1,0],[0,8,3,1]])
np.linalg.det(A)

-126.0

### Task 4###
Find the inverse of each matrix.<br>
(a) $\mathbf{A}=\begin{bmatrix}2 & 1 \\ 3 & 5 \end{bmatrix}$ <br><br>
(b) $\mathbf{A}=\begin{bmatrix}1 & 1 & 2 \\ 2 & 1 & 1 \\ 1 & 2 & 1 \end{bmatrix}$

In [ ]:
A = np.array([[2,1],[3,5]])
np.linalg.inv(A)

array([[ 0.71428571, -0.14285714],
       [-0.42857143,  0.28571429]])

In [ ]:
A = np.array([[1,1,2],[2,1,1],[1,2,1]])
np.linalg.inv(A)

array([[-0.25,  0.75, -0.25],
       [-0.25, -0.25,  0.75],
       [ 0.75, -0.25, -0.25]])

### Task 5###
Determine the norm of each of the following vectors.<br>
(a) $\mathbf{v}_1=\begin{bmatrix}2 \\ -1 \\ 1 \end{bmatrix}$ <br><br>
(b) $\mathbf{v}_2=\begin{bmatrix}4 \\ 0 \\ 3 \\ -1 \end{bmatrix}$ <br><br>
(c) $\mathbf{v}_3=\begin{bmatrix}1 \\ 0 \\ 2 \\ 2 \\ 3 \end{bmatrix}$

In [ ]:
v1 = np.array([[2],[-1],[1]])
np.linalg.norm(v1)

2.449489742783178

In [ ]:
v2 = np.array([[4],[0],[3],[-1]])
np.linalg.norm(v2)

5.0990195135927845

In [ ]:
v3 = np.array([[1],[0],[2],[2],[3]])
np.linalg.norm(v3)

4.242640687119285