# Practical 3: Applications of Matrices in Statistics

In a study on the cost of transporting milk from farms to dairy plants, a survey was taken of firms engaged in milk transportation. Cost data on $X_1$ = fuel, $X_2$ = repair and $X_3$ = capital, all measured on a per-mile basis from 34 firms were taken. The table below shows part of the data collected.

| Fuel ($X_1$) | Repair ($X_2$) | Capital ($X_3$) |
| --- | --- | --- |
| 16.44 | 12.43 | 11.23 |
| 7.19 | 2.7 | 3.92 |
| ⋮ | ⋮ | ⋮ |
| 17.32 | 6.86 | 4.44 |

(a) Plot a scatter matrix to visualise the relationship between $X_1$, $X_2$ and $X_3$. Are the data approximately multivariate normal?

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns; sns.set()
import matplotlib.pyplot as plt


In [2]:
data = pd.read_csv("Practical3.csv")
data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Practical3.csv'

In [ ]:
plt.clf()
sm = sns.pairplot(data)
plt.show()

NameError: name 'data' is not defined

<Figure size 640x480 with 0 Axes>

(b) Find the sample mean vector, sample covariance matrix and sample correlation matrix of **<span style='font-family:"Times New Roman"'> <span styel=''><font size="4">X<font>**.

In [ ]:
#Find sample mean vector. axis=0 indicates each column in the data matrix is a variable.
x_bar = np.mean(x)

In [ ]:
x_bar

29.0

In [ ]:
#Find sample covariance matrix. rowvar=0 indicates each column in the data matrix is a variable. 
C = np.cov(x, rowvar=0)

In [ ]:
x = ([10,40], [11,45], [15,53])
R = np.corrcoef(x, rowvar=0)

In [ ]:
R

array([[1.        , 0.97986371],
       [0.97986371, 1.        ]])

In [ ]:
C

array([[ 7., 17.],
       [17., 43.]])

In [ ]:
#Find sample correlation matrix
R = np.corrcoef(x, rowvar=0)

In [ ]:
R

array([[1.        , 0.97986371],
       [0.97986371, 1.        ]])

(c) Find the generalised sample variance and total sample variance.

In [ ]:
#Find generalised sample variance
np.linalg.det(C)

1052.024887663679

In [ ]:
np.trace(C)

50.0

(d) Compute the sample mean and sample variance of a firm’s operational cost of transporting milk per mile, which comprises of fuel cost and repair cost.

Let the operational cost of transporting milk be $Y_1$.<br>
$Y_1 = X_1 + X_2$

In [ ]:
#Find the data of operational cost
y1 = data.loc[:,'Fuel'] + data.loc[:,'Repair']

In [ ]:
#Find sample mean of operational cost
y1_bar = np.mean(y1, axis=0)
y1_bar

18.94470588235294

In [ ]:
#Find sample variance of operational cost
y1_C = np.cov(y1, rowvar=0)
y1_C

array(33.59521355)

(e) Compute the sample mean and sample variance of a firm’s total cost of ownership of the trucks per mile for transporting milk, which comprises of fuel cost, repair cost and capital cost.

In [ ]:
y2 = data.loc[:,'Fuel'] + data.loc[:,'Repair'] + data.loc[:,'Capital']

In [ ]:
y1

0     28.87
1      9.89
2     11.27
3     10.02
4     16.25
5     20.03
6     24.48
7     27.59
8     20.29
9     13.31
10    13.53
11    15.32
12    17.26
13    26.43
14    12.83
15    16.23
16    11.58
17    20.07
18    22.53
19    21.19
20    30.30
21    25.48
22    15.48
23    13.47
24    21.29
25    21.35
26    11.65
27    16.17
28    24.92
29    18.06
30    27.28
31    18.36
32    17.16
33    24.18
dtype: float64

In [ ]:
y2_bar = np.mean(y2, axis=0)
y2_bar


28.505882352941182

In [ ]:
y2_C = np.cov(y2, rowvar=0)
y2_C


array(60.62378859)

(f) Determine the sample sample covariance matrix for the variables in parts (d) and (e).

In [ ]:
# make data matrix Y
Y = pd.concat([y1,y2],axis=1)
# np.array([[]])
Y

In [ ]:
Y.cov()

0          1
0  33.595214  41.115829
1  41.115829  60.623789