k-Nearest Neighbor

In [1]:
# k-Nearest Neighbor
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier

# Step 1: load the data 
iris = datasets.load_iris()

In [2]:
# step 2: prepare the data
X, y = iris.data, iris.target 

# split dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [3]:
# fit a k-nearest neighbor model to the data
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)
print(model.score(X_test,y_test))

0.9666666666666667


In [4]:
# make predictions
y_pred = model.predict(X_test)

In [5]:
# summarize the fit of the model
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


Gaussian Naive Bayes

In [6]:
# Gaussian Naive Bayes
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

# Step 1: load the data 
iris = datasets.load_iris()

# step 2: prepare the data
X, y = iris.data, iris.target 

# split dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

# fit a Naive Bayes model to the data
model = GaussianNB()
model.fit(X_train, y_train)
print(model.score(X_test,y_test))

# make predictions
y_pred = model.predict(X_test)

# summarize the fit of the model
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

0.9
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.83      0.91      0.87        11
           2       0.91      0.83      0.87        12

    accuracy                           0.90        30
   macro avg       0.91      0.91      0.91        30
weighted avg       0.90      0.90      0.90        30

[[ 7  0  0]
 [ 0 10  1]
 [ 0  2 10]]


In [7]:
# Linear Regression
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression
# load the california datasets
dataset = fetch_california_housing()
# fit a linear regression model to the data
model = LinearRegression()
model.fit(dataset.data, dataset.target)
print(model)
# make predictions
expected = dataset.target
predicted = model.predict(dataset.data)
# summarize the fit of the model
mse = np.mean((predicted-expected)**2)
print(model.intercept_, model.coef_, mse)
print(model.score(dataset.data, dataset.target))

LinearRegression()
-36.94192020718435 [ 4.36693293e-01  9.43577803e-03 -1.07322041e-01  6.45065694e-01
 -3.97638942e-06 -3.78654265e-03 -4.21314378e-01 -4.34513755e-01] 0.5243209861846072
0.606232685199805
